apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-pod-watcher.fullname" . }}
  labels:
    {{- include "chart-pod-watcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart-pod-watcher.selectorLabels" . | nindent 4 }}
