apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-collector
  namespace: argocd
spec:
  project: default
  source:
    path: metrics-collector-helm
    repoURL: https://github.com/lukonjun/container-anomaly-detection.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: anomaly-detection-stack
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
