apiVersion: v1
kind: Service
metadata:
  name: chartmuseum-service
  namespace: harbor
spec:
  type: NodePort
  selector:
    component: chartmuseum
  ports:
    - port: 80
      targetPort: 9999
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: harbor
spec:
  type: NodePort
  selector:
    component: portal
  ports:
    - port: 80
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30081
