apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: anomaly-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metrics-collector
  template:
    metadata:
      labels:
        name: metrics-collector
    spec:
      serviceAccountName: metrics-collector
      containers:
        - env:
            - name: kubernetes.connect.from.outside
              value: "false"
          image: ghcr.io/lukonjun/metrics-collector:lukonjun
          name: metrics-collector-container
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          resources: {}
      restartPolicy: Always
status: {}