apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: anomaly-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metrics-collector
  template:
    metadata:
      labels:
        name: metrics-collector
    spec:
      serviceAccountName: metrics-collector
      containers:
        - env:
            - name: kubernetes.connect.from.outside
              value: "false"
            - name: influxdb.server.url
              value: "http://116.203.124.188:8086" 
            - name: influxdb.username
              value: "pod_metrics" 
            - name: influxdb.password
              value: "mypassword" 
            - name: influxdb.database
              value: "k3s_telegraf_ds" 
            - name: data.aggregator.decision.tree.classifier.list
              value: "mysql,nginx,apache,postgres,mongo"
          image: ghcr.io/lukonjun/metrics-collector:1101266046
          name: metrics-collector-container
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          resources: {}
      restartPolicy: Always
status: {}