# This is a basic workflow to help you get started with Actions
name: code integration for metrics collector
# Define environment variables here 
env:
  registry: container-registry.lukonjun.de
  image_name: library/metrics-collector

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
    - metrics-collector/**
  pull_request:
    branches: [ main ]
    paths: 
    - metrics-collector/**
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single 
  build-and-push-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Maven
      working-directory: ./metrics-collector
      run: mvn -B package --file pom.xml
    - name: GITHUB_SHA
      run: echo ${GITHUB_SHA}
    - name: Run docker build
      working-directory: ./metrics-collector
      run: docker build --tag ${{ env.registry }}/${{ env.image_name }}:latest .
    - name: Login to ${{ env.registry }} Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.registry }}
        username: admin
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Run docker push
      run: docker push ${{ env.registry }}/${{ env.image_name }}:$GITHUB_SHA
    - name: Name of Image 
      run: echo "${{ env.registry }}/${{ env.image_name }}:$GITHUB_SHA"
